spring.application.name=Mockito

#application.properties (common)
#---------------------
server.port=8080
spring.profiles.active=uat
 
#application-uat.properties (Testing)
#--------------------------
#spring.datasource.dbcp2.driver-class-name=org.h2.Driver
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.username=sa
#spring.datasource.password=password
 
#application-dev.properties (Development)
#--------------------------
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/ctsdb
#spring.datasource.username=root
#spring.datasource.password=root
#spring.jpa.hibernate.ddl-auto=update